### ISSUE TITLE
unable to find paytm jar

### ISSUE THREAD

**Issue by jagasanD** [AbhilashJain/Paytm-Payment-Spring#1]
package com.paytm.pg.merchant does not exist
just colon the project and try mvn clean install i got error unable to find the package 
So how can i fixed that issue

**Comment by AbhilashJain** [comment]
Did you add checksum.jar in your buildpath?

**Comment by jagasanD** [comment]
How can i add the checksum.jar in spring boot 
can u help i don't know please
thanks
